Introduction of the issue
While playing test with Maven ([INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] root                                                               [pom]
[INFO] the-one-with-test-jar                                              [jar]
[INFO] the-one-using-test-jar                                             [jar]
[INFO]
[INFO] ------------------------< org.test.kotlin:root >------------------------
[INFO] Building root 1.0.0-SNAPSHOT                                       [1/3]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ root ---
[INFO]
[INFO] --- kotlin:2.0.21:compile (compile) @ root ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin:2.0.21:test-compile (test-compile) @ root ---
[INFO] No sources to compile
[INFO]
[INFO] --- install:3.1.1:install (default-install) @ root ---
[INFO] Installing /Users/antoineduprat/code/kotlin-test-jar/pom.xml to /Users/antoineduprat/.m2/repository/org/test/kotlin/root/1.0.0-SNAPSHOT/root-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] ---------------< org.test.kotlin:the-one-with-test-jar >----------------
[INFO] Building the-one-with-test-jar 1.0.0-SNAPSHOT                      [2/3]
[INFO]   from the-one-with-test-jar/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ the-one-with-test-jar ---
[INFO] Deleting /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/target
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ the-one-with-test-jar ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/main/resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ the-one-with-test-jar ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin:2.0.21:compile (compile) @ the-one-with-test-jar ---
[WARNING] Source root doesn't exist: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/main/java
[INFO] Applied plugin: 'spring'
[WARNING] Using experimental Kotlin incremental compilation
[INFO] Non-incremental compilation will be performed: NO_BUILD_HISTORY
[INFO] Kotlin compile iteration: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/main/kotlin/OtherClass.kt
[INFO] Exit code: OK
[INFO] Compiled 1 Kotlin files using incremental compiler
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ the-one-with-test-jar ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/test/resources
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ the-one-with-test-jar ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin:2.0.21:test-compile (test-compile) @ the-one-with-test-jar ---
[WARNING] Source root doesn't exist: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/test/java
[INFO] Applied plugin: 'spring'
[WARNING] Using experimental Kotlin incremental compilation
[INFO] Non-incremental compilation will be performed: NO_BUILD_HISTORY
[INFO] Kotlin compile iteration: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/test/kotlin/MySharedHelper.kt, /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/src/test/kotlin/OtherClassTest.kt
[INFO] Exit code: OK
[INFO] Compiled 2 Kotlin files using incremental compiler
[INFO]
[INFO] --- surefire:3.5.2:test (default-test) @ the-one-with-test-jar ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running OtherClassTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s -- in OtherClassTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jar:3.4.2:jar (default-jar) @ the-one-with-test-jar ---
[INFO] Building jar: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/target/the-one-with-test-jar-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- jar:3.4.2:test-jar (default) @ the-one-with-test-jar ---
[INFO] Building jar: /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/target/the-one-with-test-jar-1.0.0-SNAPSHOT-tests.jar
[INFO]
[INFO] --- install:3.1.1:install (default-install) @ the-one-with-test-jar ---
[INFO] Installing /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/pom.xml to /Users/antoineduprat/.m2/repository/org/test/kotlin/the-one-with-test-jar/1.0.0-SNAPSHOT/the-one-with-test-jar-1.0.0-SNAPSHOT.pom
[INFO] Installing /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/target/the-one-with-test-jar-1.0.0-SNAPSHOT.jar to /Users/antoineduprat/.m2/repository/org/test/kotlin/the-one-with-test-jar/1.0.0-SNAPSHOT/the-one-with-test-jar-1.0.0-SNAPSHOT.jar
[INFO] Installing /Users/antoineduprat/code/kotlin-test-jar/the-one-with-test-jar/target/the-one-with-test-jar-1.0.0-SNAPSHOT-tests.jar to /Users/antoineduprat/.m2/repository/org/test/kotlin/the-one-with-test-jar/1.0.0-SNAPSHOT/the-one-with-test-jar-1.0.0-SNAPSHOT-tests.jar
[INFO]
[INFO] ---------------< org.test.kotlin:the-one-using-test-jar >---------------
[INFO] Building the-one-using-test-jar 1.0.0-SNAPSHOT                     [3/3]
[INFO]   from the-one-using-test-jar/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ the-one-using-test-jar ---
[INFO] Deleting /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/target
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ the-one-using-test-jar ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/main/resources
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ the-one-using-test-jar ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin:2.0.21:compile (compile) @ the-one-using-test-jar ---
[WARNING] Source root doesn't exist: /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/main/java
[INFO] Applied plugin: 'spring'
[INFO] Applied plugin: 'jpa'
[WARNING] Using experimental Kotlin incremental compilation
[INFO] Non-incremental compilation will be performed: NO_BUILD_HISTORY
[INFO] Kotlin compile iteration: /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/main/kotlin/SimpleClass.kt
[INFO] Exit code: OK
[INFO] Compiled 1 Kotlin files using incremental compiler
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ the-one-using-test-jar ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/test/resources
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ the-one-using-test-jar ---
[INFO] No sources to compile
[INFO]
[INFO] --- kotlin:2.0.21:test-compile (test-compile) @ the-one-using-test-jar ---
[WARNING] Source root doesn't exist: /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/test/java
[INFO] Applied plugin: 'spring'
[INFO] Applied plugin: 'jpa'
[WARNING] Using experimental Kotlin incremental compilation
[INFO] Non-incremental compilation will be performed: NO_BUILD_HISTORY
[INFO] Kotlin compile iteration: /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/src/test/kotlin/SimpleClassTest.kt
[INFO] Exit code: OK
[INFO] Compiled 1 Kotlin files using incremental compiler
[INFO]
[INFO] --- surefire:3.5.2:test (default-test) @ the-one-using-test-jar ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running SimpleClassTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.036 s <<< FAILURE! -- in SimpleClassTest
[ERROR] SimpleClassTest.testWithClassFromTestJar -- Time elapsed: 0.022 s <<< ERROR!
java.lang.NoClassDefFoundError: MySharedHelper$someKotlinCode$$inlined$sortedBy$1
	at MySharedHelper.someKotlinCode(MySharedHelper.kt:8)
	at SimpleClassTest.testWithClassFromTestJar(SimpleClassTest.kt:14)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: MySharedHelper$someKotlinCode$$inlined$sortedBy$1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SimpleClassTest.testWithClassFromTestJar:14 » NoClassDefFound MySharedHelper$someKotlinCode$$inlined$sortedBy$1
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 1.0.0-SNAPSHOT:
[INFO]
[INFO] root ............................................... SUCCESS [  0.290 s]
[INFO] the-one-with-test-jar .............................. SUCCESS [  3.583 s]
[INFO] the-one-using-test-jar ............................. FAILURE [  0.814 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.738 s
[INFO] Finished at: 2024-11-20T12:14:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.2:test (default-test) on project the-one-using-test-jar:
[ERROR]
[ERROR] See /Users/antoineduprat/code/kotlin-test-jar/the-one-using-test-jar/target/surefire-reports for the individual test results.
[ERROR] See dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :the-one-using-test-jar), an exception is raised:

it seems that the Kotlin nature of the MySharedHelper has been lost in the test-jar packaging'